# Numpy

## The Numpy Library

The NumPy library (NumPy, Numerical Python) is a package of high-level mathematical and numerical functions and tools that are designed to work with the numpy array object. A numpy array is a high performance multidimensional data structure and is all around more efficient and convenient than a Python list. 

A Python program using the numpy library may require installing the package. Additionally, a program that uses the package must include the statement:


In [2]:
import numpy

## The Numpy Array

Python deals primarily with lists and doesn't have a native array structure, so to understand the numpy array it's important to have a basic understanding of arrays. 
A one-dimensional array can be directly compared to a Python list because they both store a list of numbers. Similarly, the data in an array are called `elements` and they are accessed using brackets `[ ]`. 
A two-dimensional array has a grid structure with rows and columns. 
And a three-dimensional array can be thought of as a stack of two-dimensional arrays. 

Numpy arrays are a fixed size, indexed starting at 0, and contain elements of all the same type. They are ndarray objects and are created using the `np.array()` function.

For example

In [3]:
import numpy as np
b = np.array([1, 2, 3, 4])

The code above creates a one-dimensional array with four constants. 
Numpy arrays refer to dimensions as `axes` and the number of axes is `rank`. Therefore, b is an array of rank 1. 

There are several numpy functions for describing an array and its elements, as demonstrated in the code below:

In [5]:
import numpy as np

# Create an array of rank 2
my_arr = np.array([[1,2,3,4], [5,6,7,8]])

print(my_arr)
print(my_arr[1, 2]) # access a single element
print(my_arr.ndim) # the rank
print(my_arr.shape) # returns (n, m) --> n rows, m columns
print(my_arr.size) # number of elements 
print(type(my_arr)) # element type

[[1 2 3 4]
 [5 6 7 8]]
7
2
(2, 4)
8
<class 'numpy.ndarray'>


Note the use of brackets when creating the array. Brackets are also used when accessing an element.

---

## Creating NumPy Arrays

NumPy includes several functions for creating arrays. You can initialize arrays with ones or zeros, and you can also create arrays that are filled with constant values or random values.

In [7]:
import numpy as np

a = np.ones((3,2))  # array of 1s
print(a)

b = np.zeros((3,4)) # array of 0s
print(b)

c = np.random.random(3) # array of random value
print(c)

d = np.full((2,2),12) # array filled with constant values
print(d)  

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0.52808852 0.46208081 0.86412537]
[[12 12]
 [12 12]]


Also available is the `np.empty()` function for creating an array of uninitialized elements. 
The `np.eye()`  and ` np.identity()`  functions are for creating identity arrays for matrix calculations.

You can optionally specify the data type for array elements at the time of creation.

For example

In [6]:
d=np.full((2,2), 12, dtype=np.float32)

The `copy()` function creates a copy of an array. For example
```python
a = b.copy()
```

The `loadtxt()` function can be used to load data from a file into an array. The `save()` function is used to save a numpy array to a file.

---

## NumPy: Creating a sequence

Two useful numpy functions for creating a list of numbers that fill a range are: 
`np.arange(start, end, step)`  Creates a numpy array with elements ranging in value from start to end, incrementing by step. Only end is required. Omitting start and step creates an evenly spaced range from 0 to end.

`np.linspace(start, end, numvalues)`  Creates a numpy array with numvalues values evenly spaced from start to end.

The following code demonstrates np.arange and np.linspace:

In [8]:
import numpy as np

a = np.arange(0, 10, 2) 
print(a)

b = np.arange(6) 
print(b)

# l'ultimo parametro dice quanti elementi vengono presi
c = np.linspace(0, 10, 6)
print(c) 

[0 2 4 6 8]
[0 1 2 3 4 5]
[ 0.  2.  4.  6.  8. 10.]


Both functions evenly space values. However, the np.arange function returns values up to the end parameter, whereas the np.linspace returns a specified number of elements.

---

## NumPy: Changing Array Shape & Size

A numpy array can be reshaped and resized. 
Reshaping with `np.reshape` returns a *new* array with a modified shape and resizing with `np.resize` modifies the original array. 
A third function `np.ravel` returns a flattened array.

For example

In [14]:
import numpy as np

# Array iniziale
a = np.arange (10)
print(a)
print(a.shape) 
# (10,)

# con resize l'array originale viene modificato
a.resize(2,5) 
print(a.shape) # stampiamo shape per controllare
# (2, 5)
# nonché l'array stesso: l'array è effettivamente cambiato!
print(a)
# [[0 1 2 3 4] 
# [5 6 7 8 9]]

# Creiamo un altro array
b = np.array([[1,2,3], [4,5,6]])
print (b) 
# [[1 2 3]
# [4 5 6]]

# con reshape, invece, l'array originale non viene modificato
# ma restituito un altro array (nel nostro caso, quello che
# viene qui di seguito stampato)
print(b.reshape(3,2)) 
# [[1 2]
# [3 4] 
# [5 6]]

# stampiamo lo shape dell'array x controllare lo stato
# dell'array originale
print(b.shape)
# (2, 3)
# e l'array originale per concludere che effettivamente non è cambiato
print (b) 

# appiattiamo l'array (facendolo diventare monodimensionale)
print(b.ravel()) # or np.ravel(b)
# [1 2 3 4 5 6]
# anche in questo caso, l'array originale non è cambia
print (b.shape)
# (2, 3)
print (b) 


[0 1 2 3 4 5 6 7 8 9]
(10,)
(2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
(2, 3)
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
(2, 3)
[[1 2 3]
 [4 5 6]]


Note that reshape and ravel do not resize array b from its original shape.

The `np.transpose()` function transposes an array:

In [15]:
import numpy as np

a = np.array([[1,2,3], [4,5,6]])

print(a.transpose())

# [[1 4]

# [2 5]

# [3 6]]

[[1 4]
 [2 5]
 [3 6]]


---

## NumPy: Array Slicing

Slicing can be applied to numpy arrays as with Python lists to extract a subset of an array. *An array slice refers to the actual array elements, so changing a value in a slice changes the value in the array.*

To slice an array, you indicate the `start:stop:step` of the subset in square brackets. For example, `a[1:5:2]` returns elements 1 and 3.

For a multidimensional array, specify elements for each dimension separated by a comma. For example, `b[0:2, 1]` returns the second element (`1`) in the first two rows (`0:2`).

An ellipsis `...` is used to indicate selection along an entire dimension. For example, `b[..., 2]` returns the third element of every row.

The code below demonstrates several slicing variations:

In [20]:
import numpy as np

x = np.arange(8) # 0 1 2 3 4 5 6 7
print(x)
# [0 1 2 3 4 5 6 7]

y = x[0:4] # no step
print(y)
# [0 1 2 3]

z = x[6: ] # from element 6 on 
print(z)
# [6 7] 

print(x[ :5]) # from 0 to element 5
# [0 1 2 3 4]

z[1] = 100
# oltre ad aver modificato la fetta abbiamo modificato anche l'array originale
print(z) 
print(x) 
# [  0  1  2  3  4  5  6 100]

# altro array stavolta bidimensionale
a = np.array([[10, 11, 12, 13], [20, 22, 23, 25]])

print(a[0:1, 1]) # 2° elemento della 1a riga
# [11] 
print(a[..., 1]) # i 2° elementi di tutte le righe
# [11 22]
print(a[ : , 3]) # i 4° elementi di tutte le righe
# [13 25]

[0 1 2 3 4 5 6 7]
[0 1 2 3]
[6 7]
[0 1 2 3 4]
[  6 100]
[  0   1   2   3   4   5   6 100]
[11]
[11 22]
[13 25]


Note that when an element in array z is changed, it is also changed in the original array x.